### ISSUE TITLE
Hybrid Port Bridge Question

### ISSUE THREAD

**Issue by shuklasudhanshu** [alexey-kadyrov/hybridportbridge#4]
Hello,

Is this project is replica of Azure-Port-Bridge or you have done some customization ?
We are not able to to use Azure-Port-Bridge due to its reliability issues as it is disconnecting very frequently.

Did you use this project in any Production instance ?

**Comment by docalabs** [comment]
> Is this project is replica of Azure-Port-Bridge or you have done some customization ?

It's completely different codebase and is completely async.

> Did you use this project in any Production instance ?

Nope, I didn't use it in production. However it has extensive integration test suite.

**Comment by shuklasudhanshu** [comment]
> > Is this project is replica of Azure-Port-Bridge or you have done some customization ?
> 
> It's completely different codebase and is completely async.
> 
> > Did you use this project in any Production instance ?
> 
> Nope, I didn't use it in production. However it has extensive integration test suite.

Thanks for quick response.
